import Head from 'next/head'

export default function Home() {
  return (
    <div className=''>
      <Head>
        <title>Netflix</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className='w-full h-screen grid place-items-center'>
        
      </main>

      <footer className=''>
        
      </footer>
    </div>
  )
}
